//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSICOVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compras
    {
        public int IdCompra { get; set; }
        public int NumFac { get; set; }
        public string Detalle { get; set; }
        public int Cantidad { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        public virtual tb_Empleados tb_Empleados { get; set; }
        public virtual tb_FormaPago tb_FormaPago { get; set; }
        public virtual tb_Productos tb_Productos { get; set; }
        public virtual tb_Proveedores tb_Proveedores { get; set; }
    }
}
